spring.application.name=bibliotheque

# 1. L'adresse de ta base de données locale (3306 est le port par défaut de MySQL)
spring.datasource.url=jdbc:mysql://localhost:3306/bibliotheque?serverTimezone=UTC

# 2. Tes identifiants MySQL
spring.datasource.username=root
spring.datasource.password=Aaron2626!

# 3. La configuration de Hibernate
# "update" permet à Hibernate de s'adapter si on ajoute des choses, sans supprimer tes tables existantes
spring.jpa.hibernate.ddl-auto=update
# "true" va afficher dans ta console VS Code toutes les requêtes SQL que Hibernate écrit à ta place (super pour apprendre !)
spring.jpa.show-sql=true